// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/push_notif.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataFcmPersonal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body  string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Tag   string `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Url   string `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Icon  string `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *DataFcmPersonal) Reset() {
	*x = DataFcmPersonal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_notif_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataFcmPersonal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFcmPersonal) ProtoMessage() {}

func (x *DataFcmPersonal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_notif_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFcmPersonal.ProtoReflect.Descriptor instead.
func (*DataFcmPersonal) Descriptor() ([]byte, []int) {
	return file_proto_push_notif_proto_rawDescGZIP(), []int{0}
}

func (x *DataFcmPersonal) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DataFcmPersonal) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DataFcmPersonal) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DataFcmPersonal) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DataFcmPersonal) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DataFcmPersonal) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type DataFcmMultiple struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token []string `protobuf:"bytes,1,rep,name=token,proto3" json:"token,omitempty"`
	Title string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body  string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Tag   string   `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Url   string   `protobuf:"bytes,5,opt,name=url,proto3" json:"url,omitempty"`
	Icon  string   `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
}

func (x *DataFcmMultiple) Reset() {
	*x = DataFcmMultiple{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_notif_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataFcmMultiple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFcmMultiple) ProtoMessage() {}

func (x *DataFcmMultiple) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_notif_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFcmMultiple.ProtoReflect.Descriptor instead.
func (*DataFcmMultiple) Descriptor() ([]byte, []int) {
	return file_proto_push_notif_proto_rawDescGZIP(), []int{1}
}

func (x *DataFcmMultiple) GetToken() []string {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *DataFcmMultiple) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DataFcmMultiple) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *DataFcmMultiple) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *DataFcmMultiple) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *DataFcmMultiple) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type FcmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalSuccess int32  `protobuf:"varint,1,opt,name=totalSuccess,proto3" json:"totalSuccess,omitempty"`
	TotalFailed  int32  `protobuf:"varint,2,opt,name=totalFailed,proto3" json:"totalFailed,omitempty"`
	Message      string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *FcmResponse) Reset() {
	*x = FcmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_notif_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FcmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FcmResponse) ProtoMessage() {}

func (x *FcmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_notif_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FcmResponse.ProtoReflect.Descriptor instead.
func (*FcmResponse) Descriptor() ([]byte, []int) {
	return file_proto_push_notif_proto_rawDescGZIP(), []int{2}
}

func (x *FcmResponse) GetTotalSuccess() int32 {
	if x != nil {
		return x.TotalSuccess
	}
	return 0
}

func (x *FcmResponse) GetTotalFailed() int32 {
	if x != nil {
		return x.TotalFailed
	}
	return 0
}

func (x *FcmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Test struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Test *anypb.Any `protobuf:"bytes,1,opt,name=test,proto3" json:"test,omitempty"`
}

func (x *Test) Reset() {
	*x = Test{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_push_notif_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Test) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Test) ProtoMessage() {}

func (x *Test) ProtoReflect() protoreflect.Message {
	mi := &file_proto_push_notif_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Test.ProtoReflect.Descriptor instead.
func (*Test) Descriptor() ([]byte, []int) {
	return file_proto_push_notif_proto_rawDescGZIP(), []int{3}
}

func (x *Test) GetTest() *anypb.Any {
	if x != nil {
		return x.Test
	}
	return nil
}

var File_proto_push_notif_proto protoreflect.FileDescriptor

var file_proto_push_notif_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x75, 0x73, 0x68, 0x5f, 0x6e, 0x6f, 0x74,
	0x69, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x6e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x19, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x46,
	0x63, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12,
	0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x22, 0x89, 0x01, 0x0a, 0x0f, 0x44, 0x61, 0x74, 0x61, 0x46, 0x63, 0x6d, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63,
	0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x22, 0x6d,
	0x0a, 0x0b, 0x46, 0x63, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x46, 0x61, 0x69,
	0x6c, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x30, 0x0a,
	0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x04, 0x74, 0x65, 0x73, 0x74, 0x32,
	0xb1, 0x01, 0x0a, 0x0b, 0x46, 0x63, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x12,
	0x50, 0x0a, 0x08, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x70, 0x75,
	0x73, 0x68, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x44, 0x61, 0x74, 0x61, 0x46, 0x63, 0x6d, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x1a,
	0x1e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x63, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x50, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x12, 0x22, 0x2e,
	0x70, 0x75, 0x73, 0x68, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x46, 0x63, 0x6d, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x65, 0x1a, 0x1e, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x2e, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x46, 0x63, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_push_notif_proto_rawDescOnce sync.Once
	file_proto_push_notif_proto_rawDescData = file_proto_push_notif_proto_rawDesc
)

func file_proto_push_notif_proto_rawDescGZIP() []byte {
	file_proto_push_notif_proto_rawDescOnce.Do(func() {
		file_proto_push_notif_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_push_notif_proto_rawDescData)
	})
	return file_proto_push_notif_proto_rawDescData
}

var file_proto_push_notif_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_push_notif_proto_goTypes = []interface{}{
	(*DataFcmPersonal)(nil), // 0: push.notification.DataFcmPersonal
	(*DataFcmMultiple)(nil), // 1: push.notification.DataFcmMultiple
	(*FcmResponse)(nil),     // 2: push.notification.FcmResponse
	(*Test)(nil),            // 3: push.notification.Test
	(*anypb.Any)(nil),       // 4: google.protobuf.Any
}
var file_proto_push_notif_proto_depIdxs = []int32{
	4, // 0: push.notification.Test.test:type_name -> google.protobuf.Any
	0, // 1: push.notification.FcmPersonal.Personal:input_type -> push.notification.DataFcmPersonal
	1, // 2: push.notification.FcmPersonal.Multiple:input_type -> push.notification.DataFcmMultiple
	2, // 3: push.notification.FcmPersonal.Personal:output_type -> push.notification.FcmResponse
	2, // 4: push.notification.FcmPersonal.Multiple:output_type -> push.notification.FcmResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_push_notif_proto_init() }
func file_proto_push_notif_proto_init() {
	if File_proto_push_notif_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_push_notif_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataFcmPersonal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_notif_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataFcmMultiple); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_notif_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FcmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_push_notif_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Test); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_push_notif_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_push_notif_proto_goTypes,
		DependencyIndexes: file_proto_push_notif_proto_depIdxs,
		MessageInfos:      file_proto_push_notif_proto_msgTypes,
	}.Build()
	File_proto_push_notif_proto = out.File
	file_proto_push_notif_proto_rawDesc = nil
	file_proto_push_notif_proto_goTypes = nil
	file_proto_push_notif_proto_depIdxs = nil
}
