// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: proto/forgot_password.proto

package email

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForgotPassRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ForgotPassRequest) Reset() {
	*x = ForgotPassRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forgot_password_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgotPassRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPassRequest) ProtoMessage() {}

func (x *ForgotPassRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forgot_password_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPassRequest.ProtoReflect.Descriptor instead.
func (*ForgotPassRequest) Descriptor() ([]byte, []int) {
	return file_proto_forgot_password_proto_rawDescGZIP(), []int{0}
}

func (x *ForgotPassRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ForgotPassRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ForgotPassReseponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ForgotPassReseponse) Reset() {
	*x = ForgotPassReseponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_forgot_password_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForgotPassReseponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForgotPassReseponse) ProtoMessage() {}

func (x *ForgotPassReseponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_forgot_password_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForgotPassReseponse.ProtoReflect.Descriptor instead.
func (*ForgotPassReseponse) Descriptor() ([]byte, []int) {
	return file_proto_forgot_password_proto_rawDescGZIP(), []int{1}
}

func (x *ForgotPassReseponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_forgot_password_proto protoreflect.FileDescriptor

var file_proto_forgot_password_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x5f, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3f, 0x0a,
	0x11, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2f,
	0x0a, 0x13, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x65,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x5e, 0x0a, 0x15, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64,
	0x45, 0x6d, 0x61, 0x69, 0x6c, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x12, 0x2e, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74, 0x50, 0x61, 0x73, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x46, 0x6f, 0x72, 0x67, 0x6f, 0x74,
	0x50, 0x61, 0x73, 0x73, 0x52, 0x65, 0x73, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x17, 0x5a, 0x15, 0x2e, 0x2f, 0x6e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2f, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_forgot_password_proto_rawDescOnce sync.Once
	file_proto_forgot_password_proto_rawDescData = file_proto_forgot_password_proto_rawDesc
)

func file_proto_forgot_password_proto_rawDescGZIP() []byte {
	file_proto_forgot_password_proto_rawDescOnce.Do(func() {
		file_proto_forgot_password_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_forgot_password_proto_rawDescData)
	})
	return file_proto_forgot_password_proto_rawDescData
}

var file_proto_forgot_password_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_forgot_password_proto_goTypes = []interface{}{
	(*ForgotPassRequest)(nil),   // 0: ForgotPassRequest
	(*ForgotPassReseponse)(nil), // 1: ForgotPassReseponse
}
var file_proto_forgot_password_proto_depIdxs = []int32{
	0, // 0: ForgotPasswordService.SendEmailForgotPassword:input_type -> ForgotPassRequest
	1, // 1: ForgotPasswordService.SendEmailForgotPassword:output_type -> ForgotPassReseponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_forgot_password_proto_init() }
func file_proto_forgot_password_proto_init() {
	if File_proto_forgot_password_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_forgot_password_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgotPassRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_forgot_password_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForgotPassReseponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_forgot_password_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_forgot_password_proto_goTypes,
		DependencyIndexes: file_proto_forgot_password_proto_depIdxs,
		MessageInfos:      file_proto_forgot_password_proto_msgTypes,
	}.Build()
	File_proto_forgot_password_proto = out.File
	file_proto_forgot_password_proto_rawDesc = nil
	file_proto_forgot_password_proto_goTypes = nil
	file_proto_forgot_password_proto_depIdxs = nil
}
